#ifndef BUDDYSHARE_SHARED_CRYPTOPROVIDER_H
#define BUDDYSHARE_SHARED_CRYPTOPROVIDER_H

#include <optional>
#include <string>
#include <vector>

namespace buddyshare::shared {

// Binary byte buffer used for every raw key/plaintext/ciphertext value in this class. Base64
// text (e.g. what actually ends up in ChapterFile's JSON or access.txt) is always produced
// via base64_encode()/base64_decode() at the boundary -- CryptoProvider itself only ever
// works with raw bytes.
using Bytes = std::vector<unsigned char>;

// Result of derive_key(): the derived AES-256 key plus the random salt used to derive it. The
// salt travels alongside the ciphertext (in ChapterFile's envelope) so the same key can be
// re-derived later from the same password for decryption.
struct DerivedKey {
    Bytes key;   // 32 bytes (AES-256).
    Bytes salt;  // randomly generated by derive_key().
};

// Result of encrypt(): the random IV/nonce used plus the ciphertext. The GCM authentication
// tag (16 bytes) is appended to the end of ciphertext, not returned separately.
struct EncryptedContent {
    Bytes iv;
    Bytes ciphertext;
};

// One RSA keypair. generate_rsa_keypair() exists on this shared class (rather than only in
// test code) because spec 004's reader side needs to generate its own keypair with the exact
// same parameters this class uses to wrap/unwrap -- spec 002's writer-side flow never calls
// it itself (readers generate their own keys; see specs/002-chapter-encryption.md Scope).
struct RsaKeyPair {
    std::string public_key_base64;  // base64-encoded SPKI/DER -- access.txt's field-2 format.
    std::string private_key_pem;    // PEM. Never written to disk by this class.
};

// PBKDF2-HMAC-SHA256 / AES-256-GCM / RSA-OAEP, backed by OpenSSL -- no hand-rolled crypto.
// The single implementation shared by spec 002's writer-side encryption and spec 004's
// reader-side decryption, per specs/002-chapter-encryption.md's Architecture Context: using
// the same instance/parameters on both sides eliminates any cross-side parameter mismatch.
class CryptoProvider {
public:
    // Generates a random salt and derives a 32-byte AES-256 key from password via
    // PBKDF2-HMAC-SHA256 with a high iteration count.
    DerivedKey derive_key(const std::string& password) const;

    // Re-derives the key from password using a previously-generated salt (the decrypt path,
    // where the salt comes from the ciphertext's ChapterFile envelope).
    Bytes derive_key_with_salt(const std::string& password, const Bytes& salt) const;

    // AES-256-GCM-encrypts plaintext under key (must be 32 bytes), with a random per-call IV.
    EncryptedContent encrypt(const Bytes& plaintext, const Bytes& key) const;

    // AES-256-GCM-decrypts content under key. Returns std::nullopt -- never garbage
    // plaintext -- if the GCM authentication tag fails to verify; a wrong key/password and
    // tampered ciphertext are indistinguishable failures by design (spec 002 Edge Cases).
    std::optional<Bytes> decrypt(const EncryptedContent& content, const Bytes& key) const;

    // RSA-OAEP-encrypts aes_key under the reader's public key (base64-encoded SPKI/DER, the
    // same string AccessRegistry stores as ReaderEntry::public_key_base64).
    Bytes wrap_key(const Bytes& aes_key, const std::string& public_key_base64) const;

    // RSA-OAEP-decrypts wrapped_key under private_key_pem. Returns std::nullopt -- never
    // garbage key material -- if wrapped_key was wrapped for a different keypair.
    std::optional<Bytes> unwrap_key(const Bytes& wrapped_key, const std::string& private_key_pem) const;

    // Generates a fresh RSA keypair (2048-bit or higher). See RsaKeyPair's comment for why
    // this lives here rather than only in test code.
    static RsaKeyPair generate_rsa_keypair();

    // Extracts the base64 SPKI/DER public key embedded in private_key_pem. Spec 004's
    // ensure_local_keypair needs to redisplay a reader's public key on every run (e.g. when
    // "not registered yet"), even when reusing a previously generated keypair whose public half
    // was never stored separately -- only the private key is persisted locally. Returns
    // std::nullopt if private_key_pem doesn't parse as a valid RSA private key.
    static std::optional<std::string> public_key_from_private(const std::string& private_key_pem);

    static std::string base64_encode(const Bytes& data);
    static Bytes base64_decode(const std::string& text);
};

}  // namespace buddyshare::shared

#endif  // BUDDYSHARE_SHARED_CRYPTOPROVIDER_H
